name: village_voice
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  cloud_firestore: 4.17.5
  shared_preferences: ^2.0.15
  firebase_auth: ^4.16.0
  firebase_core: ^2.32.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.3.0
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/home_check.png
    - assets/event scedule.png
    - assets/complaint.png
    - assets/gallery.png 
    - assets/health tips.png
    - assets/emergency book.png
    - assets/woman.png
    - assets/weather update.png
    - assets/announcement.png


    


